# Global Args #################################################################
ARG BASE_UBI_IMAGE_TAG=9.4
ARG PYTHON_VERSION=3.12

# Base Layer ##################################################################
FROM registry.access.redhat.com/ubi9/ubi-minimal:${BASE_UBI_IMAGE_TAG} AS base
ARG PYTHON_VERSION
ENV PYTHON_VERSION=${PYTHON_VERSION}
WORKDIR /workspace/vllm

# Install some basic utilities ##################################################################
RUN microdnf update -y && microdnf install -y \
    python${PYTHON_VERSION}-devel python${PYTHON_VERSION}-pip python${PYTHON_VERSION}-wheel git vim gcc g++\
    && microdnf clean all

# Install build dependencies ##################################################################
RUN --mount=type=bind,source=requirements-build.txt,target=requirements-build.txt \
    python3.12 -m pip install --upgrade pip && \
    pip install -r requirements-build.txt

# Build vLLM ##################################################################
COPY . . 

ENV VLLM_TARGET_DEVICE=spyre
RUN --mount=type=bind,source=.git,target=.git \
    pip install --no-build-isolation -v -e .

CMD ["/bin/bash"]
