name: test-sypre

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-spyre:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Build docker images
      run: docker build . -t vllm-spyre -f Dockerfile.spyre
    - name: Run tests within docker image
      run: docker run -it --entrypoint /bin/bash vllm-spyre -c '''
        python3.12 -c "from transformers import pipeline; pipeline(\"text-generation\", model=\"JackFram/llama-160m\")" && \
        export VARIANT=$(ls /root/.cache/huggingface/hub/models--JackFram--llama-160m/snapshots/) && \
        mkdir -p /models && \
        ln -s /root/.cache/huggingface/hub/models--JackFram--llama-160m/snapshots/${VARIANT} /models/llama-194m && \
        pip install pytest sentence-transformers && \
        python3.12 -m pytest tests/spyre
      '''
